name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          sudo apt install -y gcc-mingw-w64 meson
          meson setup release --cross w64-mingw32.txt
          meson compile -C release

      - uses: actions/upload-artifact@v4
        with:
          path: release/src/dsound.dll
